"""Convert the generated atlas into bounded, palette/RLE firmware frames.
Requires Pillow. No image generation or artistic editing occurs here.
"""
from pathlib import Path
from PIL import Image, ImageDraw
import itertools

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/naiwa'
names = ['Sleep', 'Happy', 'Drive', 'Heart', 'Dizzy', 'Offline',
         'Curious', 'Laugh', 'Tired', 'Surprise', 'Annoyed', 'Proud']
source = Image.open(ASSETS / 'atlas.png').convert('RGB')
assert source.size == (1536, 1024), 'Atlas layout requires visual review if replaced'
# Visually inspected gutters in this generated atlas, not assumed square rows.
rows = [0, 252, 490, 728, 1024]
crops = []
for row in range(4):
    for col in range(6):
        cell = source.crop((col*256, rows[row], (col+1)*256, rows[row+1]))
        mask = Image.new('L', cell.size)
        mask.putdata([255 if min(p) < 160 else 0 for p in cell.getdata()])
        box = mask.getbbox()
        assert box
        x0,y0,x1,y1 = box
        crops.append(cell.crop((max(0,x0-3),max(0,y0-3),min(cell.width,x1+3),min(cell.height,y1+3))))
scale = min(110/max(c.width for c in crops), 120/max(c.height for c in crops))
frames = []
for crop in crops:
    crop = crop.resize((round(crop.width*scale),round(crop.height*scale)), Image.Resampling.LANCZOS)
    frame = Image.new('RGB', (128,140), 'white')
    frame.paste(crop, ((128-crop.width)//2,132-crop.height))
    frames.append(frame)
sheet = Image.new('RGB',(128*6,140*4),'white')
for i,frame in enumerate(frames): sheet.paste(frame,((i%6)*128,(i//6)*140))
palette_image = sheet.quantize(colors=256,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.NONE)
palette = palette_image.getpalette()[:768]
rgb565 = [(r>>3)<<11 | (g>>2)<<5 | (b>>3) for r,g,b in zip(palette[::3],palette[1::3],palette[2::3])]
data, offsets, decoded = [], [0], []
for i in range(24):
    frame = palette_image.crop(((i%6)*128,(i//6)*140,(i%6+1)*128,(i//6+1)*140))
    raw = list(frame.getdata())
    for value,group in itertools.groupby(raw):
        n = len(list(group))
        while n:
            count=min(n,255);data.extend((count,value));n-=count
    offsets.append(len(data))
    check=[]
    for j in range(offsets[-2],offsets[-1],2): check.extend([data[j+1]]*data[j])
    assert check == raw
    # Preview exactly the colors sent to the RGB565 display.
    out=Image.new('RGB',(128,160),'white')
    out.putdata([((rgb565[v]>>11)*255//31,((rgb565[v]>>5)&63)*255//63,(rgb565[v]&31)*255//31) for v in raw]+[(255,255,255)]*(128*20))
    ImageDraw.Draw(out).rounded_rectangle((20,146,107,149),radius=2,fill='#60e8c8')
    decoded.append(out)
def array(ctype,name,values,fmt=str):
    lines=[', '.join(fmt(v) for v in values[i:i+20]) for i in range(0,len(values),20)]
    return f'const {ctype} {name}[{len(values)}] = {{\n    '+',\n    '.join(lines)+'\n};\n'
code='/* Generated by tools/pack_naiwa.py; do not hand edit. */\n#include "naiwa_assets.h"\n'
code+=array('uint16_t','naiwa_palette',rgb565,hex)
code+=array('uint32_t','naiwa_offsets',offsets)
code+=array('uint8_t','naiwa_rle',data)
(ROOT/'main/naiwa_assets.c').write_text(code,encoding='utf-8')
(ROOT/'main/naiwa_assets.h').write_text('#pragma once\n#include <stdint.h>\n#define NAIWA_FRAMES 24\n#define NAIWA_PIXELS (128*140)\nextern const uint16_t naiwa_palette[256];\nextern const uint32_t naiwa_offsets[25];\nextern const uint8_t naiwa_rle['+str(len(data))+'];\n',encoding='utf-8')
preview=[]
for phase in range(2):
    panel=Image.new('RGB',(128*4,184*3),'#eaf0f2');draw=ImageDraw.Draw(panel)
    for face,name in enumerate(names):
        x,y=(face%4)*128,(face//4)*184
        panel.paste(decoded[face*2+phase],(x,y))
        draw.text((x+8,y+165),name,fill='#172b30')
    preview.append(panel)
preview[0].save(ASSETS/'preview.png')
preview[0].save(ASSETS/'preview.gif',save_all=True,append_images=preview[1:],duration=650,loop=0)
print(f'Packed 24 frames: {len(data)+len(offsets)*4+512:,} bytes; round-trip verified.')
