#pragma once

/* One self-contained page. Keep DOM access explicit: named-element globals such
 * as window.top are inconsistent across desktop and mobile browsers. */
static const char CAMERA_DEBUG_PAGE[] =
    "<!doctype html><html lang='zh-CN'><head><meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>ESP32 Line Vision</title><style>"
    "*{box-sizing:border-box}body{margin:0;background:#101318;color:#eef;font:14px system-ui}"
    "main{max-width:920px;margin:auto;padding:12px}h1{font-size:20px;margin:4px 0 8px}"
    ".controls{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:8px 0}"
    "label{background:#1b222c;padding:6px;border-radius:6px;font-size:12px}input{width:100%}"
    ".views{display:grid;grid-template-columns:1fr 1fr;gap:10px}.view b{display:block;margin:3px}"
    "img,canvas{display:block;width:100%;background:#222;border-radius:7px;min-height:100px}"
    "table{width:100%;border-collapse:collapse;margin-top:9px;font-size:12px;text-align:center}"
    "th,td{padding:4px 2px;border:1px solid #394452}th{background:#1b222c}"
    ".on{color:#6f6;font-weight:bold}.off{color:#f88;font-weight:bold}#msg{color:#9bd;margin-top:6px}"
    "@media(max-width:620px){.views{grid-template-columns:1fr}.controls{grid-template-columns:1fr 1fr}}"
    "</style></head><body><main><h1>四通道巡线视觉调试</h1>"
    "<div class='controls'>"
    "<label>二值阈值 <b id='thresholdValue'>30</b><input id='threshold' type='range' min='0' max='255'></label>"
    "<label>ROI 上边界 <b id='topValue'>45%</b><input id='roiTop' type='range' min='0' max='99'></label>"
    "<label>ROI 下边界 <b id='bottomValue'>100%</b><input id='roiBottom' type='range' min='1' max='100'></label>"
    "<label>ON 比例 <b id='activeValue'>8%</b><input id='activePercent' type='range' min='1' max='100'></label>"
    "</div><div class='views'><div class='view'><b>原始画面</b><img id='raw' src='/stream'></div>"
    "<div class='view'><b>二值化 + 四通道框</b><canvas id='binary'></canvas></div></div>"
    "<table><thead><tr><th>数据</th><th>CH1</th><th>CH2</th><th>CH3</th><th>CH4</th></tr></thead>"
    "<tbody><tr id='stateRow'><th>状态</th><td>-</td><td>-</td><td>-</td><td>-</td></tr>"
    "<tr id='percentRow'><th>黑色占比</th><td>-</td><td>-</td><td>-</td><td>-</td></tr>"
    "<tr id='pixelsRow'><th>黑/总像素</th><td>-</td><td>-</td><td>-</td><td>-</td></tr>"
    "<tr id='centroidRow'><th>质心 X</th><td>-</td><td>-</td><td>-</td><td>-</td></tr></tbody></table>"
    "<div id='msg'>正在等待状态数据...</div></main><script>"
    "const raw=document.querySelector('#raw'),canvas=document.querySelector('#binary'),ctx=canvas.getContext('2d');"
    "const el={threshold:document.querySelector('#threshold'),roiTop:document.querySelector('#roiTop'),roiBottom:document.querySelector('#roiBottom'),activePercent:document.querySelector('#activePercent')};"
    "const val={threshold:document.querySelector('#thresholdValue'),roiTop:document.querySelector('#topValue'),roiBottom:document.querySelector('#bottomValue'),activePercent:document.querySelector('#activeValue')};"
    "const msg=document.querySelector('#msg'),colors=['#00e5ff','#ffe600','#ff55aa','#70ff70'];let cfg=null,changeTimer=0;"
    "function cells(id){return [...document.querySelectorAll('#'+id+' td')]}"
    "function updateTable(j){const sr=cells('stateRow'),pr=cells('percentRow'),xr=cells('pixelsRow'),cr=cells('centroidRow');j.blocks.forEach((b,i)=>{sr[i].textContent=b.active?'ON':'OFF';sr[i].className=b.active?'on':'off';pr[i].textContent=b.percent+'%';xr[i].textContent=b.dark+'/'+b.total;cr[i].textContent=b.centroid_x})}"
    "function syncControls(j){for(const k of Object.keys(el)){if(document.activeElement!==el[k])el[k].value=j[k==='roiTop'?'roi_top':k==='roiBottom'?'roi_bottom':k==='activePercent'?'active_percent':k]}val.threshold.textContent=j.threshold;val.roiTop.textContent=j.roi_top+'%';val.roiBottom.textContent=j.roi_bottom+'%';val.activePercent.textContent=j.active_percent+'%'}"
    "async function status(){try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();cfg=j;syncControls(j);updateTable(j);msg.textContent=`帧 ${j.frames} | JPEG ${j.bytes} B | ${j.width}x${j.height}`;}catch(e){msg.textContent='状态读取失败: '+e.message}}"
    "function draw(){if(!cfg||!raw.naturalWidth||!raw.naturalHeight)return;const w=raw.naturalWidth,h=raw.naturalHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.drawImage(raw,0,0,w,h);const im=ctx.getImageData(0,0,w,h),p=im.data,t=cfg.threshold;for(let i=0;i<p.length;i+=4){const y=(77*p[i]+150*p[i+1]+29*p[i+2])>>8,v=y<=t?0:255;p[i]=v;p[i+1]=v;p[i+2]=v}ctx.putImageData(im,0,0);const y0=h*cfg.roi_top/100,y1=h*cfg.roi_bottom/100,bw=w/4;ctx.lineWidth=Math.max(3,w/70);ctx.font=`bold ${Math.max(12,w/18)}px sans-serif`;for(let n=0;n<4;n++){const x=n*bw,c=colors[n];ctx.fillStyle=c+'38';ctx.fillRect(x,y0,bw,y1-y0);ctx.strokeStyle=c;ctx.strokeRect(x,y0,bw,y1-y0);ctx.fillStyle='#000';ctx.fillRect(x+3,y0+3,Math.max(38,bw-6),Math.max(18,h/11));ctx.fillStyle=c;ctx.fillText('CH'+(n+1),x+6,y0+Math.max(15,h/14))}}"
    "async function sendConfig(){const top=Math.min(+el.roiTop.value,+el.roiBottom.value-1);const q=new URLSearchParams({threshold:el.threshold.value,roi_top:top,roi_bottom:el.roiBottom.value,active_percent:el.activePercent.value});try{await fetch('/config?'+q,{cache:'no-store'});await status()}catch(e){msg.textContent='参数写入失败: '+e.message}}"
    "for(const [k,input] of Object.entries(el))input.addEventListener('input',()=>{val[k].textContent=input.value+(k==='threshold'?'':'%');clearTimeout(changeTimer);changeTimer=setTimeout(sendConfig,120)});"
    "status();setInterval(status,500);setInterval(draw,160);"
    "</script></body></html>";
